### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by jlauinger** [musikcorps/webseite#8]
- [x] Create Uberspace Account
 - [x] Deploy source code
 - [x] Copy image files
 - [x] Migrate data
 - [x] Migrate Presse-Infos
 - [x] Migrate events
 - [x] Fix transparent images
 - [x] Sanity check
 - [x] Switch DNS records
 - [x] Check successful deploy
 - [x] Populate e-mail addresses
 - [x] Drink a beer
